# -*- coding: utf-8 -*-
"""DESAFIO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2YaOqGdiexleSn8r60XhGyLTBVj34Fm
"""

import numpy as np

temperaturas = np.array([25, 27, 35, 21, 24, 30, 28])

dias = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo']

import pandas as pd

data = {
    'Dia': dias,
    'Temperatura': temperaturas
}

df = pd.DataFrame(data)
print(df)
media = df['Temperatura'].mean()
print(f"Média da semana: {media:.2f}°C")

import matplotlib.pyplot as plt
plt.plot(df['Dia'], df['Temperatura'], color='blue')
plt.title('Variação da Temperatura na Semana')
plt.xlabel('Dias')
plt.ylabel('Temperatura (°C)')
plt.show()